### ISSUE TITLE
Adding setup.py

### ISSUE THREAD

**Issue by kianpu34593** [lantunes/CrystaLLM#5]
Hi,

I wonder why there isn't a setup.py in this repo for installation?

Thanks!

Best,
Kian

**Comment by lantunes** [comment]
Hi, thanks for asking this question. Can you explain why a `setup.py` script is necessary in this case? I'd like to understand the use case better. Is there something you're trying to do that can't be achieved with the current installation instructions?

Thanks,
Luis

**Comment by kianpu34593** [comment]
Hi Luis,

Yes. I would like to `pip install crystalllm` in the conda environment so that I can run it in an arbitrary directory.
Right now, when I tried to run it outside the git repo, it will output this error, which I think it stems from not being able to find crystallm module. 

```shell
-> python ../CrystaLLM/bin/sample.py \
> out_dir=../crystallm_v1_small \
> start=FILE:my_prompt.txt \
> num_samples=2 \
> top_k=10 \
> max_new_tokens=3000 \
> device=cuda
Traceback (most recent call last):
  File "/ocean/projects/cts180021p/jpu/projects/crystal_llm/random_example/../CrystaLLM/bin/sample.py", line 14, in <module>
    from crystallm import (
ModuleNotFoundError: No module named 'crystallm'
```

Thank you very much!
Kian

**Comment by lantunes** [comment]
Hi Kian,

Thanks for adding more context. I have created PR #6 to address this issue, which adds a `setup.py` file and an extra installation step to install the `crystallm` module. Please let me know if this addresses your use case.

Thanks,
Luis

**Comment by kianpu34593** [comment]
This is awesome! Thank you!
