### ISSUE TITLE
Block size of the model

### ISSUE THREAD

**Issue by ChangwenXu98** [lantunes/CrystaLLM#9]
Hi Luis, for processing the training data, it looks like the average token per cif file is smaller than the block size (768M tokens for 2.2M cif files; block size is 1024 or 2048). In that case, the sequence is very likely to contain information from two or even more cif files. However, information from different cif files are not strongly correlated, so it may not contribute to better reasoning ability of the model. Do you think it is more reasonable to decrease the block size to focus more on the local information in the current cif file?

**Comment by lantunes** [comment]
Hi @ChangwenXu98 ,

Thanks for asking this question. In the datasets I've worked with, the mean tokenized length of a CIF is ~350 tokens, but the distribution can range from less than 200 tokens to up to ~6000 tokens. I performed several experiments early on to understand how the block size affects the results. I found that doubling the block size from 1024 to 2048 didn't result in a large difference in the model's performance. By doubling the block size, we are processing more tokens per iteration, but the GPU memory requirements are doubled, and training takes longer (for the same number of iterations). I also tried two approaches to constructing the input block: randomly sampling a start index from anywhere inside a CIF (from the list of concatenated tokenized CIFs), or randomly sampling a start index that represents the first token of a CIF. I found that there isn't much difference to either approach. The only difference I seemed to notice was in the ability of the large model to generate longer CIFs (in terms of tokenized length) more successfully when a 2048 block size was used and we sampled start indices representing the beginning of a CIF.

It would be reasonable to try a smaller block size, such as 512. You'd probably want to train for twice as many iterations to see the same number of tokens as when training with a 1024 block size. But I suspect the model would have more difficulty generating longer CIFs.

Regards, 
Luis
